//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4062
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gooeycms.webrole.control.auth {
    
    
    public partial class Default {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new gooeycms.webrole.control.Secure Master {
            get {
                return ((gooeycms.webrole.control.Secure)(base.Master));
            }
        }
    }
}
