//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beachead.Web.CMS.controls {
    
    
    public partial class MarkupEditor {
        
        /// <summary>
        /// PreviewLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Anthem.LinkButton PreviewLink;
        
        /// <summary>
        /// PageMarkupText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Beachead.Web.CMS.controls.ResizableTextBox.ResizableTextBox PageMarkupText;
    }
}
